name: mlflow-ci

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: Workflow-CI/MLProject/environment.yml
          activate-environment: mlflow-env
          auto-update-conda: true

      - name: Train using MLflow
        shell: bash -l {0}
        run: |
          cd Workflow-CI/MLProject
          mlflow run .

      - name: Upload MLflow artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: Workflow-CI/MLProject/mlruns

